use novodb;

 CREATE TABLE IF NOT EXISTS Users
(
	Id_User INT AUTO_INCREMENT PRIMARY KEY,
	User_Name VARCHAR(200),
	Email VARCHAR(150),
	rol INT NOT NULL,
	Status INT NOT NULL
);
CREATE TABLE IF NOT EXISTS GRADE
(
Id_Grade INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(200),
type_Grade INT NOT NULL

);
CREATE TABLE IF NOT EXISTS Roles
(
	Id_Rol INT AUTO_INCREMENT PRIMARY KEY,
	Rol_Name VARCHAR(200),
    Jsn JSON,
	Id_Grade INT
  
) ;

ALTER TABLE Roles ADD   CONSTRAINT FOREIGN KEY (Id_Grade) REFERENCES Grade(Id_Grade);
CREATE TABLE Status 
(
Id_Status INT AUTO_INCREMENT PRIMARY KEY,
Status VARCHAR(100)
);
ALTER TABLE Users ADD   CONSTRAINT FOREIGN KEY (Status) REFERENCES Status(Id_Status);