/*/*STORE PROCEDURE PARA LA CREACIÓN DE UNA ESTATUS*/
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_CREATE_STATUS`
/*VARIBALES*/
(
_Id_Status INT,
_Status VARCHAR(100)
)
BEGIN
/*CONSULTA A LA BD*/
INSERT INTO status(Id_Status, Status)VALUE(_Id_Status,_Status);
END