/*/*STORE PROCEDURE PARA LA ACTUALIZACIONDE LA INFORMACION DENTRO DE LA TABLA
STATUS*/
CREATE PROCEDURE `SP_UPDATE_STATUS`
/*DECLARACIÓN DE VARIABLES*/
(IN _Id_Status INT,IN _Status VARCHAR(100))
BEGIN
/*CONSULTA A LA BD*/
UPDATE status SET Status= _Status WHERE Id_Status = _Id_Status;
END