/*/*STORE PROCEDURE PARA LA CREACION DE JERARQUIAS*/
CREATE PROCEDURE `SP_CREATE_GRADES`
/*DECLARACIÓN DE VARIABLES*/
(
_name VARCHAR(100),
_type_grade INT
)
BEGIN
/*CONSULTA A LA BD*/
INSERT INTO grade( name, type_grade) VALUE (_name,_type_grade);
END