/* tabla boats */
DROP PROCEDURE IF EXISTS SP_READ_BOATS;
DROP PROCEDURE IF EXISTS SP_CREATE_BOAT;
DROP PROCEDURE IF EXISTS SP_UPDATE_BOAT;
DROP PROCEDURE IF EXISTS SP_DELETE_BOAT;

/* tabla slip_types */
DROP PROCEDURE IF EXISTS SP_READ_SLIP_TYPES;
DROP PROCEDURE IF EXISTS SP_CREATE_SLIP_TYPE;
DROP PROCEDURE IF EXISTS SP_UPDATE_SLIP_TYPE;
DROP PROCEDURE IF EXISTS SP_DELETE_SLIP_TYPE;

/* tabla slips_occupation */
DROP PROCEDURE IF EXISTS SP_READ_SLIPS_OCCUPATION;
DROP PROCEDURE IF EXISTS SP_CREATE_SLIP_OCCUPATION;
DROP PROCEDURE IF EXISTS SP_UPDATE_SLIP_OCCUPATION;
DROP PROCEDURE IF EXISTS SP_DELETE_SLIP_OCCUPATION;

/* tabla slips */
DROP PROCEDURE IF EXISTS SP_READ_SLIPS;
DROP PROCEDURE IF EXISTS SP_CREATE_SLIP;
DROP PROCEDURE IF EXISTS SP_UPDATE_SLIP;
DROP PROCEDURE IF EXISTS SP_DELETE_SLIP;

/* tabla socket_types */
DROP PROCEDURE IF EXISTS SP_READ_SOCKET_TYPES;
DROP PROCEDURE IF EXISTS SP_CREATE_SOCKET_TYPE;
DROP PROCEDURE IF EXISTS SP_UPDATE_SOCKET_TYPE;
DROP PROCEDURE IF EXISTS SP_DELETE_SOCKET_TYPE;

/* tabla cable_types */
DROP PROCEDURE IF EXISTS SP_READ_CABLE_TYPES;
DROP PROCEDURE IF EXISTS SP_CREATE_CABLE_TYPE;
DROP PROCEDURE IF EXISTS SP_UPDATE_CABLE_TYPE;
DROP PROCEDURE IF EXISTS SP_DELETE_CABLE_TYPE;

