/* tabla boats */
DROP PROCEDURE IF EXISTS SP_READ_BOATS;
DROP PROCEDURE IF EXISTS SP_CREATE_BOAT;
DROP PROCEDURE IF EXISTS SP_UPDATE_BOAT;
DROP PROCEDURE IF EXISTS SP_DELETE_BOAT;

/* tabla slip_types */
DROP PROCEDURE IF EXISTS SP_READ_SLIP_TYPES;
DROP PROCEDURE IF EXISTS SP_CREATE_SLIP_TYPE;
DROP PROCEDURE IF EXISTS SP_UPDATE_SLIP_TYPE;
DROP PROCEDURE IF EXISTS SP_DELETE_SLIP_TYPE;

