/* DROP STORE PROCEDURES OF Electronic_Signature_Historic_Types */
DROP PROCEDURE IF EXISTS SP_CREATE_ELECTRONIC_SIGNATURE_HISTORIC_TYPE;
DROP PROCEDURE IF EXISTS SP_DELETE_ELECTRONIC_SIGNATURE_HISTORIC_TYPE;
DROP PROCEDURE IF EXISTS SP_READ_ELECTRONIC_SIGNATURE_HISTORIC_TYPE;
DROP PROCEDURE IF EXISTS SP_UPDATE_ELECTRONIC_SIGNATURE_HISTORIC_TYPE;

/* DROP STORE PROCEDURES OF Electronic_Signature_Historics */
DROP PROCEDURE IF EXISTS SP_CREATE_ELECTRONIC_SIGNATURE_HISTORIC;
DROP PROCEDURE IF EXISTS SP_DELETE_ELECTRONIC_SIGNATURE_HISTORIC;
DROP PROCEDURE IF EXISTS SP_READ_ELECTRONIC_SIGNATURE_HISTORIC;
DROP PROCEDURE IF EXISTS SP_UPDATE_ELECTRONIC_SIGNATURE_HISTORIC;

/* DROP STORE PROCEDURES OF Electonic_Signatures */
DROP PROCEDURE IF EXISTS SP_CREATE_ELECTRONIC_SIGNATURES;
DROP PROCEDURE IF EXISTS SP_DELETE_ELECTRONIC_SIGNATURES;
DROP PROCEDURE IF EXISTS SP_READ_ELECTRONIC_SIGNATURES;
DROP PROCEDURE IF EXISTS SP_UPDATE_ELECTRONIC_SIGNATURES;