/*/*STORE PROCEDURE PARA LA CREACION DE ROLES*/
CREATE PROCEDURE `SP_CREATE_ROLES`
/*DECLARACIÓN DE VARIABLES*/
(
 _Rol_Name VARCHAR(100), 
 _Jsn JSON, 
 _Id_Grade INT
 )
BEGIN
/*CONSULTA A LA BD*/
INSERT INTO roles (Rol_Name,Jsn,Id_Grade) 
VALUE(_Rol_Name,_Jsn,_Id_Grade);
END