/*/*STORE PROCEDURE PARA ELIMINAR DATOS DENTRO DE LA TABLA ROLES*/
CREATE PROCEDURE `SP_DELETE_ROLES` 
/*DECLARACIÓN DE VARIBLES*/
(_Id_Rol INT)

BEGIN
/*CONSULTA A LA BD*/
DELETE FROM roles WHERE Id_Rol = _Id_Rol;
END
