use novodb;
/* /* CREACIÓN DE LA TABLA USUARIOS*/
 CREATE TABLE IF NOT EXISTS users
(
	id_user INT AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(200) NOT NULL UNIQUE INDEX,
	email VARCHAR(150)  NOT NULL UNIQUE,
	rol INT NOT NULL,
	status INT NOT NULL
);

/*  CREACIÓN DE LA TABLA JERARQUIAS*/
CREATE TABLE IF NOT EXISTS grade
(
id_grade INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(200)  NOT NULL UNIQUE,
type_grade INT NOT NULL
);

/*  CREACIÓN DE LA TABLA ROLES*/
CREATE TABLE IF NOT EXISTS roles
(
	id_roles INT AUTO_INCREMENT PRIMARY KEY,
	rol_name VARCHAR(200)  NOT NULL UNIQUE,
    jsn JSON  NOT NULL ,
	id_grade INT NOT NULL
  
) ;


/*  CREACIÓN DE LA TABAL ESTATUS*/
CREATE TABLE IF NOT EXISTS status 
(
id_status INT AUTO_INCREMENT PRIMARY KEY,
status VARCHAR(100) NOT NULL UNIQUE
);

/*CREACION DE TABLA INCIDENTS*/
CREATE TABLE IF NOT EXISTS Incidents (
	incident_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	employee_id INT NOT NULL,
	incident_type_id INT NOT NULL,
	title VARCHAR(55) NOT NULL,
	description VARCHAR(255),
	date DATE
);

/*CREACION DE TABLA INCIDENTS_TYPE*/
CREATE TABLE IF NOT EXISTS incidents_type(
incident_type_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
inicdent_type VARCHAR(55) NOT NULL
);