use novodb;
/* /* CREACIÓN DE LA TABLA USUARIOS*/
 CREATE TABLE IF NOT EXISTS Users
(
	Id_User INT AUTO_INCREMENT PRIMARY KEY,
	User_Name VARCHAR(200),
	Email VARCHAR(150),
	rol INT NOT NULL,
	Status INT NOT NULL
);

/*  CREACIÓN DE LA TABLA JERARQUIAS*/
CREATE TABLE IF NOT EXISTS GRADE
(
Id_Grade INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(200),
type_Grade INT NOT NULL
);

/*  CREACIÓN DE LA TABLA ROLES*/
CREATE TABLE IF NOT EXISTS Roles
(
	Id_Rol INT AUTO_INCREMENT PRIMARY KEY,
	Rol_Name VARCHAR(200),
    Jsn JSON,
	Id_Grade INT
  
) ;


/*  CREACIÓN DE LA TABAL ESTATUS*/
CREATE TABLE IF NOT EXISTS Status 
(
Id_Status INT AUTO_INCREMENT PRIMARY KEY,
Status VARCHAR(100)
);

/*CREACION DE TABLA INCIDENTS*/
CREATE TABLE IF NOT EXISTS Incidents (
	Incident_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Employee_id INT,
	Incident_type_id INT,
	Title VARCHAR(55),
	Description VARCHAR(255),
	date DATE
);

/*CREACION DE TABLA INCIDENTS_TYPE*/
CREATE TABLE IF NOT EXISTS Incidents_Type(
Incident_type_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
INCIDENTS_TYPE VARCHAR(55)
);