/*/*STORE PROCEDURE PARA LA ELIMINACION DE  USUARIOS DE MANERA LOGICA*/
CREATE  PROCEDURE `SP_UPDATE_STATUS_USERS`
/*DECLARACIÓN DE VARIABLES*/
(
IN V_Id_User INT,
IN V_Status INT)
BEGIN
/*CONSULTA A LA BD*/
UPDATE USERS SET Status = V_Status WHERE Id_User = V_Id_User;
END