/*/*STORE PROCEDURE PARA ELIMINAR DATOS DENTRO DE LA TABLA STATUS*/
CREATE PROCEDURE `SP_DELETE_STATUS`
/*DECLARACIÓN DE VARIBLES*/
(_id_status INT)
BEGIN
/*CONSULTA A LA BD*/
DELETE FROM status WHERE id_Status = _id_status;
END