/*/*STORE PROCEDURE PARA LA ACTUALIZACIONDE LA INFORMACION DENTRO DE LA TABLA
STATUS*/
CREATE PROCEDURE `SP_UPDATE_STATUS`
/*DECLARACIÓN DE VARIABLES*/
(IN _id_status INT,IN _status VARCHAR(100))
BEGIN
/*CONSULTA A LA BD*/
UPDATE status SET Status= _status WHERE id_status = _id_status;
END