/* Borra todos los rows previos */
DELETE FROM notification_status;
TRUNCATE TABLE notification_status;

CALL SP_CREATE_NOTIFICATION_STATUS("Enviado");
CALL SP_CREATE_NOTIFICATION_STATUS("Pendiente");
CALL SP_CREATE_NOTIFICATION_STATUS("Guardado");
CALL SP_CREATE_NOTIFICATION_STATUS("Eliminado");

CALL SP_READ_NOTIFICATION_STATUS();

CALL SP_DELETE_NOTIFICATION_STATUS(1);

CALL SP_UPDATE_NOTIFICATION_STATUS(3, "Detenido");
CALL SP_READ_NOTIFICATION_STATUS();