/* DROP STORE PROCEDURES OF Marina_Quotations */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_QUOTATION;;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_QUOTATION;
DROP PROCEDURE IF EXISTS SP_LOGICAL_DELETED_MARINA_QUOTATION;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_QUOTATION;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_QUOTATIONS_LIST;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_QUOTATION;

/* DROP STORE PROCEDURES OF Marina_Mooring_Rates */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_MOORING_RATE;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_MOORING_RATE;
DROP PROCEDURE IF EXISTS SP_LOGICAL_DELETED_MARINA_MOORING_RATE;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_MOORING_RATE;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_MOORING_RATE;

/* DROP STORE PROCEDURES OF Marina_Mooring_Rates_Types */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_MOORING_RATE_TYPE;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_MOORING_RATE_TYPE;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_MOORING_RATE_TYPE;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_MOORING_RATE_TYPE;

/* DROP STORE PROCEDURES OF Marina_Moratorium_Charge */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_MORATORIUM_CHARGE;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_MORATORIUM_CHARGE;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_MORATORIUM_CHARGE;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_MORATORIUM_CHARGE;

/* DROP STORE PROCEDURES OF Marina_Payment_Moratorium_Charge */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_PAYMENT_MORATORIUM_CHARGE;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_PAYMENT_MORATORIUM_CHARGE;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_PAYMENT_MORATORIUM_CHARGE;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_PAYMENT_MORATORIUM_CHARGE;

/* DROP STORE PROCEDURES OF Marina_Payment_Quotation_Debt */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_PAYMENT_QUOTATION_DEBT;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_PAYMENT_QUOTATION_DEBT;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_PAYMENT_QUOTATION_DEBT;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_PAYMENT_QUOTATION_DEBT;

/* DROP STORE PROCEDURES OF Marina_Payment_Services */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_PAYMENT;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_PAYMENT;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_PAYMENT_SERVICE;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_PAYMENT;

/* DROP STORE PROCEDURES OF Marina_Payments */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_PAYMENT;
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_PAYMENT;
DROP PROCEDURE IF EXISTS SP_READ_MARINA_PAYMENT;
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_PAYMENT;

/* DROP STORE PROCEDURES OF Marina_Quotation_Debts */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_QUOTATION_DEBT
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_QUOTATION_DEBT
DROP PROCEDURE IF EXISTS SP_READ_MARINA_QUOTATION_DEBT
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_QUOTATION_DEBT

/* DROP STORE PROCEDURES OF Marina_Quotation_Services */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_QUOTATION_SERVICE
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_QUOTATION_SERVICE
DROP PROCEDURE IF EXISTS SP_LOGICAL_DELETED_MARINA_QUOTATION_SERVICE
DROP PROCEDURE IF EXISTS SP_READ_MARINA_QUOTATION_SERVICE
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_QUOTATION_SERVICE

/* DROP STORE PROCEDURES OF Marina_Quotation_Status */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_QUOTATION_STATUS
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_QUOTATION_STATUS
DROP PROCEDURE IF EXISTS SP_READ_MARINA_QUOTATION_STATUS
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_QUOTATION_STATUS

/* DROP STORE PROCEDURES OF Marina_Services */
DROP PROCEDURE IF EXISTS SP_CREATE_MARINA_SERVICE
DROP PROCEDURE IF EXISTS SP_DELETE_MARINA_SERVICE
DROP PROCEDURE IF EXISTS SP_READ_MARINA_SERVICE
DROP PROCEDURE IF EXISTS SP_UPDATE_MARINA_SERVICE

/* DROP STORE PROCEDURES OF Payment_Methods */
DROP PROCEDURE IF EXISTS SP_CREATE_PAYMENT_METHOD
DROP PROCEDURE IF EXISTS SP_DELETE_PAYMENT_METHOD
DROP PROCEDURE IF EXISTS SP_READ_PAYMENT_METHOD
DROP PROCEDURE IF EXISTS SP_UPDATE_PAYMENT_METHOD