/*/*STORE PROCEDURE PARA LA ELIMINACIÓN DE DATOS DENTRO DE LA TABLA JERAQUIA*/
CREATE PROCEDURE `SP_DELETE_GRADE` 
/*DECLARACION DE VARIABLES*/
(_Id_Grade INT)
BEGIN
/*CONSULTA A LA BD*/
DELETE FROM grade WHERE Id_Grade = _Id_Grade;
END
