/*/*STORE PROCEDURE MODIFICACIÓN DE DATOS DENTRO DE LA TABLA JERARQUIA*/
CREATE PROCEDURE `SP_UPDATE_GRADE` 
/*DECLARACIÓN DE VARIABLES´*/
(
_Id_Grade INT,
_Name VARCHAR(100),
_type_Grade INT
)
BEGIN
/*CONSULTA A LA BD*/
UPDATE grade SET  
Name = _Name, 
type_Grade = _type_Grade 
WHERE Id_Grade = _Id_Grade;
END
