TRUNCATE TABLE IF EXISTS users;
TRUNCATE TABLE IF EXISTS status;
TRUNCATE TABLE IF EXISTS roles;
TRUNCATE TABLE IF EXISTS ranks;
TRUNCATE TABLE IF EXISTS incidents;
TRUNCATE TABLE IF EXISTS incident_types;