/*/*STORE PROCEDURE PARA ELIMINAR DATOS DENTRO DE LA TABLA ROLES*/
CREATE PROCEDURE `SP_DELETE_ROLES` 
/*DECLARACIÓN DE VARIBLES*/
(_id_rol INT)

BEGIN
/*CONSULTA A LA BD*/
DELETE FROM roles WHERE id_rol = _id_rol;
END
