/*/*STORE PROCEDURE PARA LA ELIMINACIÓN DE UNA USUARIOS*/
CREATE PROCEDURE `SP_DELETE_USERS`
/*DECLARACIÓN DE VARIABLES*/
(
v_id_user INT
)
BEGIN
/*CONSULTA A LA BD*/
DELETE FROM users WHERE id_user = v_id_user;
END