/*/*STORE PROCEDURE PARA LA ELIMINACION DE  USUARIOS DE MANERA LOGICA*/
CREATE  PROCEDURE `SP_UPDATE_STATUS_USERS`
/*DECLARACIÓN DE VARIABLES*/
(
IN v_id_user INT,
IN v_status INT)
BEGIN
/*CONSULTA A LA BD*/
UPDATE users SET status = v_status WHERE id_user = v_id_user;
END