/* Borra todos los rows previos */
DELETE FROM boat_electricity;
TRUNCATE TABLE boat_electricity;

CALL SP_CREATE_BOAT_ELECTRICITY(1, 1, 1);
CALL SP_CREATE_BOAT_ELECTRICITY(2, 1, 1);
CALL SP_CREATE_BOAT_ELECTRICITY(3, 3, 3);
CALL SP_CREATE_BOAT_ELECTRICITY(4, 4, 4);
CALL SP_CREATE_BOAT_ELECTRICITY(5, 2, 1);


CALL SP_READ_BOAT_ELECTRICITY();

CALL SP_DELETE_BOAT_ELECTRICITY(5);
CALL SP_UPDATE_BOAT_ELECTRICITY(2, 1, 1, 1);
CALL SP_READ_BOAT_ELECTRICITY();


