/* Borra todos los rows previos */
DELETE FROM boat_document_types;
TRUNCATE TABLE boat_document_types;

CALL SP_CREATE_BOAT_DOCUMENT_TYPE("Seguro de Barco", 1);
CALL SP_CREATE_BOAT_DOCUMENT_TYPE("Acta", 0);
CALL SP_CREATE_BOAT_DOCUMENT_TYPE("Permiso de Amarre", 1);

CALL SP_READ_BOAT_DOCUMENT_TYPES();

CALL SP_DELETE_BOAT_DOCUMENT_TYPE(1);

CALL SP_UPDATE_BOAT_DOCUMENT_TYPE(2, "Acta Oficial", 0);
CALL SP_READ_BOAT_DOCUMENT_TYPES();