/* tabla slip_types */
DROP PROCEDURE IF EXISTS SP_SlipTypes_GetSlipTypes;
DROP PROCEDURE IF EXISTS SP_SlipTypes_PostSlipType;

/* tabla slips_occupation */
DROP PROCEDURE IF EXISTS SP_CREATE_SLIP_OCCUPATION;
DROP PROCEDURE IF EXISTS SP_DELETE_SLIP_OCCUPATION;
DROP PROCEDURE IF EXISTS SP_SlipsOccupation_GetSlipsOccupation;
DROP PROCEDURE IF EXISTS SP_UPDATE_SLIP_OCCUPATION;

/* tabla slips */
DROP PROCEDURE IF EXISTS SP_Slips_GetSlips;
DROP PROCEDURE IF EXISTS SP_Slips_PostSlip;
