CALL SP_CREATE_MARINA_QUOTATION(1, 1, 2, 1, '2019-05-19', '2019-05-20', 0, 12.0, 42, 3, 30, 20.3, 10.3, 1000.3, 100.3, false, false, true, 'Default User');

CALL SP_CREATE_MARINA_QUOTATION_STATUS("Borrador");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Enviado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Aceptado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Válidado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Declinado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Sin Pagos"); 
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Pago Parcial"); 
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Cargo Moratorio"); 
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Suspensión");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Pagado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Terminado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Cancelado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Caducado");
CALL SP_CREATE_MARINA_QUOTATION_STATUS("Eliminado");
    