/* Borra todos los rows previos */
DELETE FROM engines;
TRUNCATE TABLE engines;

CALL SP_CREATE_ENGINE(1, "MTU", "S 60");
CALL SP_CREATE_ENGINE(1, "MTU", "S 60");
CALL SP_CREATE_ENGINE(2, "MTU", "8V 2000 M94");
CALL SP_CREATE_ENGINE(3, "YANMAR", "H23");

CALL SP_READ_ENGINES();

CALL SP_DELETE_ENGINE(2);

CALL SP_UPDATE_ENGINE(4, 3, "YANMAR", "H232");
CALL SP_READ_ENGINES();